module.exports = {
    product_name: "Yagate Kimi ni Naru",
    product_volume: 1,
    product_price: 8.90,
    product_author: "Nakatani Nio",
    product_category: "Yuri",
    product_add: false,
    product_rank: 4,
    product_img: "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/6269/9781626923539.jpg",
    product_desc: "Bloom into You is an ongoing series and will be released as single volumes with at least one full colour illustration per book. Yuu has always loved shoujo manga and awaits the day she gets a love confession that sends her heart aflutter with bubbles and hearts, and yet when a junior high classmate confesses his feelings to her...she feels nothing. Disappointed and confused, Yuu enters high school still unsure howto respond. That's when Yuu sees the beautiful student council president Nanami turn down a suitor with such maturity that she's inspired to ask her for help. But when the next person to confess to Yuu is Nanami herself, has her shoujo romance finally begun?",
    product_format: "Paperback",
    product_pages: 180,
    product_dimention: "127 x 180 x 10mm | 136, 08g",
    product_publish_day: "03 Jan 2017",
    product_editor: "Seven Seas Entertainment, LLC",
    product_publish_location: "West Hollywood, United States",
    product_languaje: "English",
    product_ISBN10: 1626923531,
    product_ISBN13: 978,
    product_selling_rank: 5231,
    product_similar: JSON.stringify(["Citrus", "Sadamaki Koto"]),
    //product_seller: 1,
    product_percentage: 11,
    product_total_sell: 0,
}